In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

Multi-dimensional Arrays

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(x)
print()

print(x.shape)
print()

print(x.ndim) # number of dimensions
print()


[[1 2 3]
 [4 5 6]
 [7 8 9]]

(3, 3)

2



Changing dimension of an array

In [16]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array:")
print(x)


print("change dimension of the array:")
x = np.array([1, 2, 3, 4, 5, 6], ndmin=4)
print(x)

Original array:
[1 2 3 4 5 6]
change dimension of the array:
[[[[1 2 3 4 5 6]]]]


In [17]:
type(x)

numpy.ndarray

n-dimensional indexing

In [ ]:
# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# accessing 8
print(arr[2][1])

8


In [24]:
# 3D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
# accessing 9
print(arr[1][0][2])

9


Array slicing

x[start:end:steps]

In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

even = arr[1::2]
print(even)

odd = arr[0::2]
print(odd)

reverse = arr[::-1]
print(reverse)

[ 2  4  6  8 10]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]


In [29]:
# 2D array slicing
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

2D array slicing

arr[row, start:end:step]

In [31]:
arr[2, 1::]

array([12, 13, 14, 15])

numpy data types

In [33]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x.dtype)

y= np.array(['apple', 'banana', 'cherry'])
print(y.dtype)

int64
<U6


Iterator

In [34]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [36]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[1:, ::2]):
  print(x)

5
7
