In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

Multi-dimensional Arrays

In [4]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(x)
print()

print(x.shape)
print()

print(x.ndim) # number of dimensions
print()


[[1 2 3]
 [4 5 6]
 [7 8 9]]

(3, 3)

2



Changing dimension of an array

In [5]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array:")
print(x)


print("change dimension of the array:")
x = np.array([1, 2, 3, 4, 5, 6], ndmin=4)
print(x)

Original array:
[1 2 3 4 5 6]
change dimension of the array:
[[[[1 2 3 4 5 6]]]]


In [6]:
type(x)

numpy.ndarray

n-dimensional indexing

In [7]:
# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
# accessing 8
print(arr[2][1])

8


In [9]:
# 3D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
# accessing 9
print(arr[1][0][2])

9


Array slicing

x[start:end:steps]

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

even = arr[1::2]
print(even)

odd = arr[0::2]
print(odd)

reverse = arr[::-1]
print(reverse)

[ 2  4  6  8 10]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]


In [12]:
# 2D array slicing
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

2D array slicing

arr[row, start:end:step]

In [13]:
arr[2, 1::]

array([12, 13, 14, 15])

numpy data types

In [14]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x.dtype)

y= np.array(['apple', 'banana', 'cherry'])
print(y.dtype)

int64
<U6


Iterator

In [15]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[1:, ::2]):
  print(x)

5
7


shape and reshape

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)

(2, 3)


In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)
print()
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

(2, 2, 3)


In [22]:
# reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# unknown dimension marks with -1 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, -1, 3) # -1 means "unspecified"
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Convert nD array to 1D array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8 9]


search and sort

In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

index = np.where(arr == 5)
print(index)

(array([4]),)


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
index = np.where(arr == 5)
print(index)

(array([1]), array([1]))


join & split

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr1 = np.array_split(arr, 5)
print(arr1)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [36]:
# join arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

[1 2 3 4 5 6]
